AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: photo-LF1
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LF1/LF1.zip
      Description: 'Index Function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::682475076944:role/photo-LF'
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: photo-s3-chenli
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          REGION: us-east-1
